(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* Initialization stuff; of no intrinsic interest *)
ClearAll["Global`*"];
If[Length[$FrontEnd] > 0,NBDir=SetDirectory[NotebookDirectory[]]];(* If running from the Notebook interface *)
(* If running from shell, must start from inside same directory in which notebook resides so that $InitialDirectory has the right value *)
(* Method of displaying figures depends on whether being run in batch mode or interactively *)
If[$FrontEnd == Null,OpenFigsUsingShell=True,OpenFigsUsingShell=False]; 
(* Current working directory should correspond to appropriate location now whether running from shell or notebook *)
Get["./init.m"];
(* Configure various parameters *)
FigDir="../../Figures";


kBarOptimal=((\[CapitalXi] \[Bet]-1)/\[CurlyEpsilon])^(1/(\[CurlyEpsilon]-1));
kBarActual=(\[CapitalXi] (1+\[Beta])/((1-\[CurlyEpsilon])\[Beta]))^(1/(\[CurlyEpsilon]-1));


NextStepk[k_] := \[ScriptCapitalQ] k^\[CurlyEpsilon];
NextStepArrows[k_,HeadSize_] := Show[
Graphics[{Thickness[Medium],Arrowheads[{{HeadSize,1,Graphics[Polygon[{{0, 0}, {-1, Rational[-1, 3]}, {Rational[-1, 3], 0}, {-1, Rational[1, 3]}}], ImageSize -> {38., Automatic}]}}],Arrow[{{k,NextStepk[k]},{NextStepk[k],NextStepk[k]}}]}],Graphics[{Thickness[Medium],Arrowheads[{{HeadSize,1,Graphics[Polygon[{{0, 0}, {-1, Rational[-1, 3]}, {Rational[-1, 3], 0}, {-1, Rational[1, 3]}}], ImageSize -> {38., Automatic}]}}],Arrow[{{NextStepk[k],NextStepk[k]},{NextStepk[k],NextStepk[NextStepk[k]]}}]}]];


\[CurlyEpsilon] = 0.33; (* Elasticity of output with respect to capital/labor ratio; 'capital share' *)
YearsPerGeneration=30; (* A 'period' in a 2-period life *)
\[Beta] = 0.96^YearsPerGeneration;\[Bet]=0.995^YearsPerGeneration;
\[CapitalXi] = 1.01^YearsPerGeneration;
\[Xi]=\[CapitalXi]-1;
\[ScriptCapitalQ] = (1-\[CurlyEpsilon])(\[Beta]/(1+\[Beta]))/\[CapitalXi];
kBar = \[ScriptCapitalQ]^(1/(1-\[CurlyEpsilon]));
kMax = 0.05;


PlotOLG = Plot[ \[ScriptCapitalQ] k^\[CurlyEpsilon],{k,0,kMax}
,Ticks->None
,PlotRange->{{0,kMax},{0,kMax}}
];
Degree45 = Plot[ k,{k,0,kMax}
,Ticks->None
,PlotRange->{{0,kMax},{0,kMax}}
,PlotStyle->{Thickness[Medium],Dashing[{0.03}]}
];


Initialk=0.01;ArrowHeadSize=0.025;
SteadyStateLine = Graphics[{Dashing[{0.02}],Line[{{kBar,0},{kBar,kMax}}]}];
InitialPoint = Graphics[{Thickness[Medium],Arrowheads[{{ArrowHeadSize,1,Graphics[Polygon[{{0, 0}, {-1, Rational[-1, 3]}, {Rational[-1, 3], 0}, {-1, Rational[1, 3]}}], ImageSize -> {38., Automatic}]}}],Arrow[{{Initialk,0},{Initialk,NextStepk[Initialk]}}]}];OLGModelDynamics = Show[
PlotOLG
,Degree45
,InitialPoint
,NextStepArrows[NextStepk[.01],ArrowHeadSize]
,NextStepArrows[.01,ArrowHeadSize]
,SteadyStateLine
,Graphics[Text["45\[Degree] Line\[RightArrow]",{.047,.047},{1,-1}]]
,Graphics[Text["\!\(\*SubscriptBox[\(k\), \(1\)]\) \[LongRightArrow] ",{Initialk,NextStepk[Initialk]},{1,0}]]
,Graphics[Text["\!\(\*SubscriptBox[\(k\), \(t + 1\)]\)(\!\(\*SubscriptBox[\(k\), \(t\)]\)) \[LongRightArrow] ",{.02,NextStepk[.02]},{1,0}]]
,ImageSize->{72 6.,72 6./GoldenRatio}
,AxesLabel->{"\!\(\*SubscriptBox[\(k\), \(t\)]\)","\!\(\*SubscriptBox[\(k\), \(t + 1\)]\)"}
,Ticks->{{{kBar,"\!\(\*OverscriptBox[\(k\), \(_\)]\)"},{Initialk,"\!\(\*SubscriptBox[\(k\), \(0\)]\)"}},None}
];
ExportFigsToDir["OLGModelDynamics",FigDir];


(* Now analyze model described in handout SocSecAndKAccum *)


NextStepk[k_] := \[ScriptCapitalQ] k^\[CurlyEpsilon]-.013;
Print[kBarBar = (kSeek/. FindRoot[kSeek ==  \[ScriptCapitalQ] kSeek^\[CurlyEpsilon] - .013,{kSeek,.01,.03}])];


kBarForcMax=(\[Xi]/\[CurlyEpsilon])^(1/(\[CurlyEpsilon]-1));
kBarForcZero=\[Xi]^(1/(\[CurlyEpsilon]-1));
fBase=Plot[k^\[CurlyEpsilon],{k,0,kBarForcZero}];
nkBase=Plot[\[Xi]  k,{k,0,kBarForcZero},PlotStyle->{Thickness[Medium],Dashing[{0.02}]}];
fAndnkPlot=Show[fBase
,nkBase
,Graphics[Text["\[LongLeftArrow] \[Xi]k",{kBarForcZero/2, \[Xi] kBarForcZero/2},{-1,0}]]
,Graphics[Text["f(k)\[LongRightArrow]",{kBarForcZero(3/4),( kBarForcZero(3/4))^\[CurlyEpsilon]},{1,0}]]
,AxesLabel->{"k","        "}
,Ticks->None];
fMinusnkBase=Plot[{k^\[CurlyEpsilon]-\[Xi]  k},{k,0,kBarForcZero}];
fMinusnkPlot=Show[fMinusnkBase
,Graphics[Text["\[LongLeftArrow] f(k)-\[Xi]k",{kBarForcZero(3/4),(kBarForcZero(3/4))^\[CurlyEpsilon]- \[Xi] kBarForcZero(3/4)},{-1,0}]]
,AxesLabel->{"k","f(k)-\[Xi]k"},Ticks->None];
fnkBoth=Show[GraphicsGrid[{{fAndnkPlot},{fMinusnkPlot}}]];
ExportFigsToDir["fAndnkPlot",FigDir];
ExportFigsToDir["fMinusnkPlot",FigDir];
ExportFigsToDir["fnkBoth",FigDir];


NewSteadyStateLine = Graphics[{Dashing[{0.02}],Line[{{kBarBar,0},{kBarBar,kMax}}]}];
PlotOLGwSS = Plot[ NextStepk[k],{k,0,kMax},Ticks->None];
OriginalSSPoint = Graphics[{Thickness[Medium],Arrowheads[{{ArrowHeadSize,1,Graphics[Polygon[{{0, 0}, {-1, Rational[-1, 3]}, {Rational[-1, 3], 0}, {-1, Rational[1, 3]}}], ImageSize -> {38., Automatic}]}}],Arrow[{{kBar,kBar},{kBar,NextStepk[kBar]}}]}];


(* Generates figures for handout on Social Security and capital accumulation *)
SocSecAndKAccum = Show[PlotOLG
,Degree45
,PlotOLGwSS
,OriginalSSPoint
,Graphics[Text["45\[Degree] Line\[RightArrow]",{.047,.047},{1,-1}]]
,SteadyStateLine
,NewSteadyStateLine
,NextStepArrows[kBar,NextStepk[kBar]]
,NextStepArrows[NextStepk[kBar],ArrowHeadSize]
,AxesLabel->{"\!\(\*SubscriptBox[\(k\), \(t\)]\)","\!\(\*SubscriptBox[\(k\), \(t + 1\)]\)"}
,Ticks->{{{kBarBar,"\!\(\*OverscriptBox[OverscriptBox[\(k\), \(_\)], \(_\)]\)"},{kBar,"\!\(\*OverscriptBox[\(k\), \(_\)]\)"}},None}
];
ExportFigsToDir["SocSecAndKAccum","../../../SocSecAndKAccum/Figures"];


(* Now produce graphs used in OLG problem set/exam questions *)


(* Effect of a sudden permanent increase in growth *)


\[CapitalXi] = 1.0^YearsPerGeneration;
\[Xi]=\[CapitalXi]-1;
\[Beta] = .96^YearsPerGeneration;
\[GothicCapitalG]=1.01^YearsPerGeneration;
\[GothicG]=\[GothicCapitalG]-1;
\[ScriptCapitalQ] = (1-\[CurlyEpsilon])(\[Beta]/(1+\[Beta]))/\[GothicCapitalG];
kBar = \[ScriptCapitalQ]^(1/(1-\[CurlyEpsilon]));
PlotOLG = Plot[ \[ScriptCapitalQ] k^\[CurlyEpsilon],{k,0,kMax}
,Ticks->None
,PlotRange->{{0,kMax},{0,kMax}}
];


InitialSteadyStateLine = Graphics[{Dashing[{0.02}],Line[{{kBar,0},{kBar,kMax}}]}];
\[GothicCapitalG]=1.03^YearsPerGeneration;
\[GothicG]=\[GothicCapitalG]-1;
\[ScriptCapitalQ]=\[ScriptCapitalQ]New = (1-\[CurlyEpsilon])(\[Beta]/(1+\[Beta]))/\[GothicCapitalG];
kBarNew = \[ScriptCapitalQ]^(1/(1-\[CurlyEpsilon]));

PlotOLGNew = Plot[ \[ScriptCapitalQ]New k^\[CurlyEpsilon],{k,0,kMax}
,Ticks->None
,PlotRange->{{0,kMax},{0,kMax}}
];



NextStepk[k_] := \[ScriptCapitalQ] k^\[CurlyEpsilon];
InitialPoint=Graphics[{PointSize[0.015],Point[{kBar,kBar}]}];
FinalPoint=Graphics[{PointSize[0.015],Point[{kBarNew,kBarNew}]}];
 
InitialJump = Graphics[{Arrowheads[{{ArrowHeadSize,1,Graphics[Polygon[{{0, 0}, {-1, Rational[-1, 3]}, {Rational[-1, 3], 0}, {-1, Rational[1, 3]}}], ImageSize -> {38., Automatic}]}}],Arrow[{{kBar,kBar},{kBar,NextStepk[kBar]}}]}];
Print[OLGGorNShockConverge = Show[
PlotOLG
,Degree45
,PlotOLGNew
,InitialPoint
,FinalPoint
,InitialJump
,NextStepArrows[kBar,ArrowHeadSize]
,Graphics[Text["45\[Degree] Line\[RightArrow]",{.047,.047},{1,-1}]]
,Graphics[Text["\[UpperLeftArrow]\!\(\*SubscriptBox[OverscriptBox[\(k\), \(^\)], \(t + 1\)]\)(\!\(\*SubscriptBox[\(k\), \(t\)]\))",{.041,NextStepk[.02]},{-1,-1}]]
,AxesLabel->{"\!\(\*SubscriptBox[\(k\), \(t\)]\)","\!\(\*SubscriptBox[\(k\), \(t + 1\)]\)"}
,Ticks->{{{kBar,"\!\(\*OverscriptBox[\(k\), \(_\)]\)"},{kBarNew,"\!\(\*OverscriptBox[OverscriptBox[\(k\), \(^\)], \(_\)]\)"}},None}
]];



ExportFigsToDir["OLGGorNShockConverge",FigDir];




